[book]
authors = ["Matt Mastracci", "Estefania Barreto-Ojeda"]
language = "en"
src = "src"
title = "crok Documentation"
description = "Documentation and reference guide for the crok tool"

[preprocessor.crok]

[output.html]
no-section-label = true

# Waiting for linkcheck to update
#[output.linkcheck]
